### ISSUE TITLE
Missing socials in update profile

### ISSUE THREAD

**Issue by hayuna** [Geeks-Academy/structure#168]
Affected user: 60dcb3df6926a22d2b81268a

Details: When I put anything in the socials (facebook, patron, linkedin, yt) and saved it, then opened it again and I cannot see patreon, linkedin, yt icons

<img width="1161" alt="Screenshot 2021-07-09 at 17 04 55" src="https://user-images.githubusercontent.com/19636010/125099114-f8b2f400-e0d7-11eb-9cb3-798cfe77751f.png">

Additionally I can see these socials assigned to user, but in the view we can see only one (facebook)

<img width="744" alt="Screenshot 2021-07-09 at 17 11 27" src="https://user-images.githubusercontent.com/19636010/125099811-b63de700-e0d8-11eb-938c-1687d9f35bf3.png">

**Comment by zeglarz** [comment]
U mnie ten problem nie występuje. Gdy dodam nowy social do danego usera, zapisuje, wchodzę na rekord i poprawnie pojawiają mi się wszystkie sociale. Również na wskazanym przez Ciebie userze.

**Comment by hayuna** [comment]
Steps to reproduce:
1. Open update panel http://localhost:3000/admin/edit/60dcb3df6926a22d2b81268a
2. Click on the last social (gitlab)

Where is facebook now? Neither on the social list nor on the used social list

<img width="1080" alt="Screenshot 2021-07-09 at 19 44 25" src="https://user-images.githubusercontent.com/19636010/125117165-13906300-e0ee-11eb-8e76-0dd032220a98.png">
