### ISSUE TITLE
We can see additional social icon

### ISSUE THREAD

**Issue by hayuna** [Geeks-Academy/structure#169]
Affected user: 60dcb3df6926a22d2b81268a

As in the screenshot, we can see 
1. additional social icon, with incorrect title (telegram) and/or icon (hejto)
2. This icon is the same we can see in the previous line. (double hejto icon, double telegram title) 

<img width="646" alt="Screenshot 2021-07-09 at 17 13 37" src="https://user-images.githubusercontent.com/19636010/125100196-1cc30500-e0d9-11eb-90a3-d5dd51702b9c.png">

**Comment by zeglarz** [comment]
to nie jest mój bug, ten element zwracany jest przez api

   {
        "active": false,
        "_id": "60db6a971edef169b26c0153",
        "name": "telegram",
        "image": "https://res.cloudinary.com/mras2303/image/upload/v1621368298/social_icons/hejto.png",
        "__v": 0
    }
