### ISSUE TITLE
Weird behaviour in social component

### ISSUE THREAD

**Issue by hayuna** [Geeks-Academy/structure#170]
Affected user: 60dcb3df6926a22d2b81268a

* Details
When we are clicking socials from the right to left socials are wiped out

<img width="1150" alt="Screenshot 2021-07-09 at 17 19 01" src="https://user-images.githubusercontent.com/19636010/125100813-d02bf980-e0d9-11eb-87e7-f30086b5151c.png">

**Comment by zeglarz** [comment]
It's not a bug, it's a feature. This functionality was requested in the task description: 
![image](https://user-images.githubusercontent.com/29867856/125115773-15f1bd80-e0ec-11eb-8737-376908a149dc.png)

**Comment by hayuna** [comment]
So where is gitlab on this list?
<img width="1854" alt="Screenshot 2021-07-09 at 19 46 46" src="https://user-images.githubusercontent.com/19636010/125117522-a92bf280-e0ee-11eb-9417-f7b743aab4b3.png">
