### ISSUE TITLE
Improve Error handling in controllers

### ISSUE THREAD

**Issue by hayuna** [Geeks-Academy/structure#46]
We can find this part of code is repeating

```javascript
try {
    …
  } catch (error) {
    console.log(error)
    res.status(StatusCode.INTERNAL_SERVER_ERROR).json({ message: error.message });
  }
```

**Comment by PiotrGrobelak** [comment]
I tried to create something reusable. But I'm not sure if this pattern will be fine. I wait for opinion :)

**Comment by hayuna** [comment]
https://zellwk.com/blog/async-await-express/#express-async-handler
