### ISSUE TITLE
New Slack Project Notifier

### ISSUE THREAD

**Issue by bwieckow** [Geeks-Academy/structure#52]
Basing on this https://github.com/goodroot/github-action-slack-project-notifier we need to create a better tool which will let you customize following fields:

- username                               (optional, default: GitHub Projects)
- text                                         (optional, default: Status for the ticket has changed.)
- icon_emoji                              (optional, default: :github: - you can propose some better option )
- color                                       (optional: default: #ffdd00)
- SLACK_WEBHOOK_URL          (required)
- PROJECT                                 (required)
- TOKEN                                    (required)

and change `"title": "Project Name",` to `"title": "Ticket Name",` in line 43 in `index.js`

**Comment by hayuna** [comment]
Please specify which properties are required and which values are expected/default in them

**Comment by bwieckow** [comment]
@hayuna description updated.
